[tool.poetry]
name = "fetch-agents"
version = "0.1.0"
description = ""
authors = ["Fatumayattani <fyattani@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uagents = "^0.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
